app = "platform-perevaga"
primary_region = "ams"

[build]
  image = "dmytro24tar/perevaga:latest"
  
[env]
  ASPNETCORE_URLS="http://+:8080"
  EmailOptions__SenderEmail="perevaga.platform.ua@gmail.com"
  EmailOptions__SenderName="Perevaga"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
